# Generated by Django 5.2.4 on 2025-07-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEACHERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, help_text='LaTeX formatida variant matni', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='LaTeX formatida savol matni', null=True),
        ),
    ]
