# Generated by Django 5.2.4 on 2025-07-28 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEACHERS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.PositiveIntegerField(default=10, help_text='Test davomiyligi (daqiqada)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
